<div class="container-fluid">
    <div class="page-title">
        Latest Generated Sessions
    </div>
    <p class="text-muted">View and Edit Sessions Generated by the system</p>
<div class="table-responsive">
    <table id="smartClassSessionTable" class="table table-bordered table-hover table-striped w-100">
        <thead class="table-dark">
            <tr>
                <th data-priority="1">📅 Date</th>
                <th data-priority="2">🕘 Time</th>
                <th data-priority="3">📍 Location</th>
                <th data-priority="4">✅ Status</th>
                <th data-priority="5">📝 Notes</th>
                <th data-priority="6">⚙️ Action</th>
            </tr>
        </thead>
        <tbody>
            @if($sessions->isEmpty())
            <tr>
                <td colspan="6" class="text-center">No sessions found 💤</td>
            </tr>
            @else
                @foreach($sessions as $session)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($session->session_date)->format('d F Y') }}</td>
                    <td>{{ \Carbon\Carbon::parse($session->start_time)->format('H:i') }} - {{ \Carbon\Carbon::parse($session->end_time)->format('H:i') }}</td>
                    <td>{{ $session->location }}</td>
                    <td>{{ $session->status }}</td>
                    <td>{{ $session->notes }}</td>
                    <td><a href="{{ route('admin_edit_session', $session->id) }}" class="btn btn-sm btn-warning">edit</a></td>
                </tr>
                @endforeach
            @endif
        </tbody>
    </table>
</div>
</div>
<script>
    $('#smartClassSessionTable').DataTable({
      responsive: true,
      pageLength: 10,
      lengthChange: false,
      ordering: true,
      dom: 'tip',
      order: [[0, 'asc']],
    });
</script>
